"""All the key sequences"""

CURTSIES_NAMES = dict([
  (' ',        '<SPACE>'),
  ('\x1b ',    '<Meta-SPACE>'),
  ('\t',       '<TAB>'),
  ('\x1b[Z',   '<Shift-TAB>'),
  ('\r',       '<RETURN>'),
  ('\n',       '<RETURN>'),
  ('\x1b[A',   '<UP>'),
  ('\x1b[B',   '<DOWN>'),
  ('\x1b[C',   '<RIGHT>'),
  ('\x1b[D',   '<LEFT>'),
  ('\x1bOA',   '<Esc+UP>'),
  ('\x1bOB',   '<Esc+DOWN>'),
  ('\x1bOC',   '<Esc+RIGHT>'),
  ('\x1bOD',   '<Esc+LEFT>'),
  ('\x1bOP',   '<F1>'),
  ('\x1bOQ',   '<F2>'),
  ('\x1bOR',   '<F3>'),
  ('\x1bOS',   '<F4>'),
  ('\x1b[15~', '<F5>'),
  ('\x1b[17~', '<F6>'),
  ('\x1b[18~', '<F7>'),
  ('\x1b[19~', '<F8>'),
  ('\x1b[20~', '<F9>'),
  ('\x1b[21~', '<F10>'),
  ('\x1b[23~', '<F11>'),
  ('\x1b[24~', '<F12>'),
  ('\x1b\x7f', '<Meta-DELETE>'),
  ('\x00', '<Ctrl-SPACE>'),
  ('\x1c', r'<Ctrl-\>'),
  ('\x1d', '<Ctrl-]>'),
  ('\x1e', '<Ctrl-6>'),
  ('\x1f', '<Ctrl-/>'),
  ('\x7f', '<DELETE>'),
  ('\x1b\x7f', '<Meta-DELETE>'),
  ('\xff', '<Meta-DELETE>'),
  ('\x1b\x1b[A',   '<Meta-UP>'),
  ('\x1b\x1b[B',   '<Meta-DOWN>'),
  ('\x1b\x1b[C',   '<Meta-RIGHT>'),
  ('\x1b\x1b[D',   '<Meta-LEFT>'),
  ('\x1b',   '<ESC>'),
  ])
