"""All the key sequences"""

CURTSIES_NAMES = dict([
  (b' ',          u'<SPACE>'),
  (b'\x1b ',      u'<Meta-SPACE>'),
  (b'\t',         u'<TAB>'),
  (b'\x1b[Z',     u'<Shift-TAB>'),
  (b'\r',         u'<RETURN>'),
  (b'\n',         u'<RETURN>'),
  (b'\x1b[A',     u'<UP>'),
  (b'\x1b[B',     u'<DOWN>'),
  (b'\x1b[C',     u'<RIGHT>'),
  (b'\x1b[D',     u'<LEFT>'),
  (b'\x1bOA',     u'<Esc+UP>'),
  (b'\x1bOB',     u'<Esc+DOWN>'),
  (b'\x1bOC',     u'<Esc+RIGHT>'),
  (b'\x1bOD',     u'<Esc+LEFT>'),
  (b'\x1bOP',     u'<F1>'),
  (b'\x1bOQ',     u'<F2>'),
  (b'\x1bOR',     u'<F3>'),
  (b'\x1bOS',     u'<F4>'),
  (b'\x1b[15~',   u'<F5>'),
  (b'\x1b[17~',   u'<F6>'),
  (b'\x1b[18~',   u'<F7>'),
  (b'\x1b[19~',   u'<F8>'),
  (b'\x1b[20~',   u'<F9>'),
  (b'\x1b[21~',   u'<F10>'),
  (b'\x1b[23~',   u'<F11>'),
  (b'\x1b[24~',   u'<F12>'),
  (b'\x1b\x7f',   u'<Meta-DELETE>'),
  (b'\x00',       u'<Ctrl-SPACE>'),
  (b'\x1c',       u'<Ctrl-\\>'),
  (b'\x1d',       u'<Ctrl-]>'),
  (b'\x1e',       u'<Ctrl-6>'),
  (b'\x1f',       u'<Ctrl-/>'),
  (b'\x7f',       u'<DELETE>'),
  (b'\x1b\x7f',   u'<Meta-DELETE>'),
  (b'\xff',       u'<Meta-DELETE>'),
  (b'\x1b\x1b[A', u'<Meta-UP>'),
  (b'\x1b\x1b[B', u'<Meta-DOWN>'),
  (b'\x1b\x1b[C', u'<Meta-RIGHT>'),
  (b'\x1b\x1b[D', u'<Meta-LEFT>'),
  (b'\x1b',       u'<ESC>'),
  ])
